config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  root "homes#top"
  get "home/about" => "homes#about", as: "about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorite, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
  end
  get "/search", to: "searches#search"
  resources :chats, only: [:show, :create, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :favorites, dependent: :destroy
  has_many :month_favorites, -> { where(created_at: 3.month.ago.beginning_of_day..Time.current.end_of_day) }
  has_many :notifications, as: :notifiable, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  after_create do
    user.followers.each do |follower|
      notifications.create(user_id: follower.id)
    end
  end  

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      Book.where(title: content)
    elsif method == 'forward'
      Book.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      Book.where('name LIKE ?', '%' + content)
    else
      Book.where('name LIKE ?', '%' + content + '%')
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user,only: [:edit, :destroy, :update]

  def show
    @book = Book.find(params[:id])
    @book.increment!(:view_count)
    @user = @book.user
    @book_new = Book.new
    @book_comment = BookComment.new
    
  end

  def index
    @books = Book.all
    to = Time.current.at_end_of_day
    from = (to - 1.month).at_beginning_of_day
    @books = Book.includes(:favorites).sort_by {
      |book| -book.favorites.where(created_at: from...to).count
    }
    @book = Book.new
    @user = User.find(current_user.id)
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      flash[:notice] = "errors prohibited this obj from being saved;"
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      @books = Book.all
      flash[:notice] = "errors prohibited this obj from being saved:"
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user_id == current_user.id
      redirect_to books_path
    end
  end
end

app/views/books/_form.html.erb
<%= form_with model: book do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit "Create Book", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td>
          <%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td>
        <td id="favorite_btn_<%= book.id %>">
          <%= render "favorites/btn", book: book %>
        </td>
      　<td>
      　 <%= link_to "#{book.book_comments.count}コメント", book_path(book.id) %>
      　</td>
      </tr>
      <tr>
      　<td>
      　  閲覧数: <%= book.view_count %>
      　</td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book_new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td>
            <%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"50x50" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td>
            <%= link_to @book.title, @book %>
          </td>
          <td>
            <%= @book.body %>
          </td>
          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
          <% end %>
        </tr>
        <tr>
          <td id="favorite_btn_<%= @book.id %>">
            <%= render "favorites/btn", book: @book %>
          </td>
        </tr>
        <tr>
            <% @book.book_comments.each do |book_comment| %>
            <td>
              <%= image_tag book_comment.user.get_profile_image, width: 50, height: 50 %>
            </td>
            <td>
              <%= book_comment.user.name %>
              <%= book_comment.created_at.strftime('%Y/%m/%d') %>
              <%= book_comment.comment %>
            </td>
            <td>
              <% if book_comment.user == current_user %>
                <%= link_to "destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-danger pull-right" %>
              <% end %>
            </td>
            <% end %>
        </tr>
      </table>
      <table>
        <tr>
          <td>
            コメント数：<%= @book.book_comments.count %>
          </td>
        </tr>
        <tr>
          <td>
            閲覧数: <%= @book.view_count %>
          </td>
        </tr>
      </table>
      <%= form_with model: [@book, @book_comment], local: false do |f| %>
        <%= f.text_area :comment, size: "55x5" %>
        <br>
        <%= f.submit "送信" %>
      <% end %>
    </div>
  </div>
</div>